# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - allow:
      - dependency-type: all
    directory: /
    package-ecosystem: composer
    schedule:
      interval: weekly
      day: wednesday
    versioning-strategy: increase
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: wednesday

